name: Update KenPom Links

on:
  workflow_dispatch:

jobs:
  kp_update_links:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.SDV_GH_TOKEN }}
      KP_USER: ${{ secrets.KP_USER }}
      KP_PW: ${{ secrets.KP_PW }}

  scrape-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setting up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            sportsdataverse/sportsdataverse-data
            ropensci/piggyback

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      # Tells Github to run the file `scraper.py` from your repository
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
      - name: Run Scraper
        run: python scrape_mbb_json.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add .
          git commit -m "MBB Year Updated" || echo "No changes to commit"
          git pull --rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
